### ISSUE TITLE
Bind to a local TCP port

### ISSUE THREAD

**Issue by vorakl** [pgul/udp-link#1]
Hi @pgul,

`udp-link` works great! 
I quickly tested  it on a couple scenarios, e.g.  ssh connections and transfer files to a tcp daemon. No issues.

I think, it would be cool if `udp-link` could bind to a local TCP port and go to the background so it can be used as a proxy.

**Comment by vorakl** [comment]
As a follow up, it is not a super urgent feature that cannot be achieved in other ways.
For example, a similar local binding can be implemented with `socat`:

in one terminal execute:
`$ socat TCP-LISTEN:1234 SYSTEM:"udp-link -t 127.0.0.1\:22 remote.host.org"`

and then in another execute:
`$ ssh -p 1234 -i ~/.ssh/id_rsa user@127.0.0.1`

It'd just be much nicer to have it builtin ;)

**Comment by pgul** [comment]
Hi,
thank you for testing and feedback.

For this feature udp-link should support multiple tcp sessions within a single udp link. Or dynamically create links (and fork the process on the sides) on a new tcp connection to the local side.
It is possible, but this feature is more complex, requires protocol changes, and I'm not sure when I have time to implement it.

But can't this be achieved by ssh "-L" option with udp-link as a proxy?

**Comment by vorakl** [comment]
Sure,  'ssh -L' or socat would work just fine, depending on the need to encrypt the channel. 
Agreed, it's not worth the time to implement something that hardly anyone will use.
I'll close the issue.
