### ISSUE TITLE
How to interpret "Incorrect YAK" and "Received data packet" error messages? 

### ISSUE THREAD

**Issue by vorakl** [pgul/udp-link#2]
Hi @pgul,

For the testing purposes, I created two connections from one laptop to two different VMs but on one remote network (in the cloud, virtualized). One connection dropped by some reason, in the logs I found only a message that it was closed by client. (I reconnected manually). The 2nd connection is still alive. I don't know how to troubleshoot this case...

Anyway, for the rest of the time, I see a bunch of messages in logs (see below). IP addresses didn't change in this period of time and I sent nothing to the remote. I just keep terminals open. 

It's quite weird that it often receives a packet that one number less than expected...
Although, connections are good, I can use both terminals.
Is it normal? What do they mean?

```
Jan 13 19:30:18 node1.amd64 udp-link[1410269]: TCP connected to 127.0.0.1 127.0.0.1:22
Jan 13 19:30:19 node1.amd64 udp-link[1410269]: Connection established
Jan 13 19:30:26 node1.amd64 udp-link[1410269]: Received data packet with seq 10, expected 11, ignored
Jan 13 19:30:30 node1.amd64 udp-link[1410269]: Received data packet with seq 19, expected 20, ignored
Jan 13 19:30:39 node1.amd64 udp-link[1410269]: Received data packet with seq 30, expected 31, ignored
Jan 13 19:30:42 node1.amd64 udp-link[1410269]: Received data packet with seq 40, expected 41, ignored

Jan 14 00:46:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
Jan 14 00:47:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
Jan 14 00:48:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
Jan 14 00:51:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
Jan 14 00:52:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
Jan 14 00:53:11 node1.amd64 udp-link[1410269]: Incorrect YAK (buffer is empty), ignored
```

Another interesting observation is that a 2nd connection has much less error messages, although, they both are initiated from the same host:

```
Jan 13 19:30:27 node2.amd64 udp-link[1233971]: TCP connected to 127.0.0.1 127.0.0.1:22
Jan 13 19:30:27 node2.amd64 udp-link[1233971]: Connection established
Jan 13 19:31:21 node2.amd64 udp-link[1233971]: Received data packet with seq 10, expected 11, ignored
Jan 13 19:44:48 node2.amd64 udp-link[1233971]: Received data packet with seq 24, expected 25, ignored
```

**Comment by vorakl** [comment]
There is definitely some issue with transferring data. I tested of a random 100MB file. On my channel, the upload total traffic on the interface was 12 Mbit/s the whole time of transmitting data, but scp some times reported 1-1.2 MB/s and no errors from `udp-link` in logs, sometimes, I saw a lot of those errors, and the speed was dropping to 80-90 KB/s. Although, the traffic on the channel was still the same, around 12 Mbit/s. If I started over the process again, it was uploaded with no errors and on 1MB/s again. More over, on every test, I got the correct file on the remote side (sha256sum). It seems, `udp-link` rejects a lot of packets and has to re-transmit them again, but I didn't notice any correlation to the environment. I restarted many times in a row and there were no guaranteed stable results.

The good thing is that for remote shells that's not a big issue and my connections to the remote are alive for a couple days now and survived multiple IP addresses and outgoing channels changes ;)

**Comment by pgul** [comment]
Hi.
Thank you for the feedback.

udp-link resends a data packet if it has not received confirmation for some time, initially 500 ms. So, if the confirmation is received later, the data packet will be resent, and on the remote side the data packet will be received twice, with message "Received data packet with seq 10, expected 11, ignored". In this case the remote side may assume that confirmation (I choose "YAK" for this, not usual "ACK") was lost and send the confirmation for that second packet. On the local side this will be an unexpected YAK, and it will be ignored (with debug message about it).

So it's ordinary behavior, nothing bad.

udp-link has not been optimized for transfer speed, the main goal is working with unreliable connections. I think transfer speed may be limited due to not large window, buffer for unconfirmed packets. I'll try to extend the buffer (when I have time for it).

**Comment by pgul** [comment]
I've added some improvements for batch transfer (scp) in udp-link v0.5. On my tests the transfer speed now is even better than with raw tcp (without udp-link proxy).
Please test the new version (if it's still actual for you).

**Comment by vorakl** [comment]
Yes, sure, I'm using it every day!
Thanks, I'll test a new version for a few days and come back with results.

**Comment by vorakl** [comment]
`udp-link` looks pretty stable! Thanks for improving it.
